format = """
$directory\
$git_branch\
$git_status\
$git_state\
$python\
$cmd_duration\
$status\
$line_break\
$character"""

# Show ❯ in purple or red depending on exit status
[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# Show working directory
[directory]
style = "blue"

# Git branch
[git_branch]
format = "[$branch]($style)"
style = "bright-black"

# Git state (e.g. rebasing, merge)
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

# Git status indicators (unstaged, staged, ahead, etc.)
[git_status]
format = "  ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "✖"
untracked = "?"
modified = "M"
staged = "+"
renamed = "R"
deleted = "D"
stashed = "≡"

# Python virtualenv
[python]
format = "[$virtualenv]($style) "
style = "bright-black"

# Show duration if command took more than 2s
[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "yellow"

# Red X if last command failed
[status]
style = "bold red"
symbol = "✗ "
format = "[$symbol$status]($style) "
disabled = false
