return {
  --   {
  --     'nvim-neo-tree/neo-tree.nvim',
  --     branch = 'v3.x',
  --     dependencies = {
  --       'nvim-lua/plenary.nvim',
  --       'nvim-tree/nvim-web-devicons',
  --       'MunifTanjim/nui.nvim',
  --     },
  --     config = function()
  --       vim.fn.sign_define('DiagnosticSignError', { text = ' ', texthl = 'DiagnosticSignError' })
  --       vim.fn.sign_define('DiagnosticSignWarn', { text = ' ', texthl = 'DiagnosticSignWarn' })
  --       vim.fn.sign_define('DiagnosticSignInfo', { text = ' ', texthl = 'DiagnosticSignInfo' })
  --       vim.fn.sign_define('DiagnosticSignHint', { text = '󰌵', texthl = 'DiagnosticSignHint' })
  --
  --       require('neo-tree').setup {
  --         enable_diagnostics = true,
  --         default_component_configs = {
  --           icon = {
  --             folder_closed = '',
  --             folder_open = '',
  --             folder_empty = '󰜌',
  --             error = '',
  --             warning = '',
  --           },
  --           diagnostics = {
  --             symbols = {
  --               hint = '󰌵',
  --               info = '',
  --               warn = '',
  --               error = '',
  --             },
  --             -- Highlight groups for different diagnostic levels
  --             highlights = {
  --               hint = 'DiagnosticHint',
  --               info = 'DiagnosticInfo',
  --               warn = 'DiagnosticWarn',
  --               error = 'DiagnosticError',
  --             },
  --           },
  --           name = {
  --             trailing_slash = false,
  --             use_git_status_colors = true,
  --             highlight = 'NeoTreeFileName',
  --           },
  --
  --           git_status = {
  --             symbols = {
  --               added = '✚', -- or "✚", but this is redundant info if you use git_status_colors on the name
  --               modified = '', -- or "", but this is redundant info if you use git_status_colors on the name
  --               deleted = '✖', -- this can only be used in the git_status source
  --               renamed = '󰁕', -- this can only be used in the git_status source
  --               -- Status type
  --               untracked = '',
  --               ignored = '',
  --               unstaged = '󰄱',
  --               staged = '',
  --               conflict = '',
  --             },
  --           },
  --         },
  --         filesystem = {
  --           filtered_items = {
  --             visible = true,
  --             hide_dotfiles = true,
  --             hide_gitignored = false,
  --             never_show_by_pattern = {
  --               '.git',
  --               '.DS_Store',
  --               'thumbs.db',
  --               'desktop.ini',
  --               '__pycache__',
  --               '.vscode',
  --             },
  --           },
  --           follow_current_file = {
  --             enabled = true,
  --             leave_dirs_open = false,
  --           },
  --           hijack_netrw_behavior = 'open_default',
  --         },
  --       }
  --       vim.keymap.set('n', '<leader>e', '<cmd>Neotree toggle<CR>', { desc = 'Toggle Neotree' })
  --     end,
  --   },
}
